config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :blacklists, only: [ :new, :create, :destroy ]
  resources :users, only: [ :show, :edit, :update ]
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :listings, only: [ :index, :show, :new, :create, :destroy ] do
    resources :meetings, only: [ :create, :show ]
  end

  resources :meetings, only: [ :index, :edit, :update ]

  post 'twilio/voice' => 'twilio#voice'

  resources :chat_rooms, only: [ :show ] do
    resources :messages, only: [ :create ]
  end

  mount Attachinary::Engine => "/attachinary"
  mount ActionCable.server => "/cable"

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :meetings

  def owns_listing?(current_user)
    self.user == current_user
  end

  def photo_exist?
    self.user.facebook_picture_url == nil
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def index
    me = current_user
    # extracting Blacklist contraints
    blacklist_me = Blacklist.where(friend_id: me.id)
    blacklist_me_ids = blacklist_me.map do |blacklist|
      blacklist["user_id"]
    end

    blacklist_others = Blacklist.where(user_id: me.id)
    blacklist_others_ids = blacklist_others.map do |blacklist|
      blacklist["friend_id"]
    end
    # extracting Facebook friends
    user_friends = FacebookApiService.new(current_user.token).friends
    uids = user_friends.map do |friend|
      friend["id"]
    end

    users = User.where.not(id: blacklist_others_ids).where.not(id: blacklist_me_ids).where(uid: uids).pluck(:id)
    listings_fb = Listing.where.not(user_id: current_user.id).where(user_id: users).where(status: "open")
    # listings_local = Listing.all.where.not(user_id: current_user.id).where(status: "in use")
    # @listings = listings_fb + listings_local
    @listings = listings_fb.order('offered_datetime ASC')

     #overview of huddles I participated in
    meeting_ids = Participant.where(user_id: me.id).pluck(:meeting_id)
    meetings = Meeting.where(id: meeting_ids, status: "active")
    @listings_participation = Listing.where(id: meetings.map(&:listing_id)).order("created_at ASC")

  end

  def show
    @listing = Listing.find(params[:id])
    respond_to do |format|
      format.js {
        render :show
      }
      format.html {
        render :show
      }
    end
  end

  def new
    @listing = Listing.new

    # OPTIONS TO BE EXTRACTED FROM USER PROFILE LATER -- PERSONAL PREFERENCES
    @offered_datetime_text_options = [ "NOW", "+1h", "+2h", "TONIGHT", "EVENING", "NOON", "MORNING", "+3h", "+4h", "+5h", "+6h", "+7h", "+8h", "+9h", "+10h", "+11h", "+12h"]

    @activity_options = [  "🤷", "🍽", "🎉", "💘", "🛒", "🎵", "🍰", "🎤", "🚀", "🚴", "🤡", "💬", "🆙", "🎧", "🥘",
]
    respond_to do |format|
      format.js {
        render :new
      }
      format.html {
        render :new
        # redirect_to listing_path(@listing)
      }
    end
    # OPTIONS TO BE EXTRACTED FROM USER PROFILE LATER -- PERSONAL PREFERENCES
  end

  def create
    # @listing = Listing.create(listing_params)

    @listing = Listing.new

    @listing.offered_datetime_text = params[:listing][:offered_datetime_text]
    @listing.offered_datetime = what_is_datetime_text?(params[:listing][:offered_datetime_text])

    @listing.activity = params[:listing][:activity]

    @listing.user = User.find(current_user.id)

    @listing.save

    redirect_to listings_path
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    redirect_to listings_path
  end

  private

  def listing_params
    params.require(:listing).permit(:activity, :offered_datetime_text)
  end

  def what_is_datetime_text?(offered_datetime_text)
    return case offered_datetime_text
      when "NOW" then DateTime.now + 30.minutes
      when "+1h" then DateTime.now + 1.hours
      when "+2h" then DateTime.now + 2.hours
      when "+3h" then DateTime.now + 3.hours
      when "+4h" then DateTime.now + 4.hours
      when "+5h" then DateTime.now + 5.hours
      when "+6h" then DateTime.now + 6.hours
      when "+7h" then DateTime.now + 7.hours
      when "+8h" then DateTime.now + 8.hours
      when "+9h" then DateTime.now + 9.hours
      when "+10h" then DateTime.now + 10.hours
      when "+11h" then DateTime.now + 11.hours
      when "+12h" then DateTime.now + 12.hours
      when "TONIGHT" then DateTime.now.change({ hour: 22 })
      when "MORNING" then DateTime.now.change({ hour: 9})
      when "NOON" then DateTime.now.change({ hour: 12})
      when "EVENING" then DateTime.now.change({ hour: 18})
    end
  end

    # def translate_datetime_back_to_text(datetime)
    #   return case datetime
    #   when datetime == hour: 22 then "TONIGHT"
    #   when datetime == hour: 9 then "MORINING"
    #   when datetime == hour: 12 then "NOON"
    #   when datetime == hour: 18 then "EVENING"
    #   end
    #   now = Time.now
    #   time_difference = datetime - now
    #   return case time_difference
    #   when time_difference < 1.hour then "NOW"
    #   when time_difference > 1.hour then "+1h"
    #   when time_difference > 2.hours then "+2h"
    #   when time_difference > 3.hours then "+3h"
    #   when time_difference > 4.hours then "+4h"
    #   when time_difference > 5.hours then "+5h"
    #   when time_difference > 6.hours then "+6h"
    #   when time_difference > 7.hours then "+7h"
    #   when time_difference > 8.hours then "+8h"
    #   when time_difference > 9.hours then "+9h"
    #   when time_difference > 10.hours then "+10h"
    #   when time_difference > 11.hours then "+11h"
    #   when time_difference > 12.hours then "+12h"
    #   end
    # end



end

app/views/listings/_new_plan.html.erb
<div class="container-fluid">
  <div class="add-plan-wrapper">
    <div class="row">
      <div id="add-plan">

        <% content_for :navbar_title do %>
        What do you want to do?
        <% end %>

        <div class="form">


          <%= simple_form_for(listing) do |f| %>
          <%= f.error_notification %>


          <%= f.hidden_field :offered_datetime_text, value: offered_datetime_text_options[0]  %>
          <%= f.hidden_field :activity, value: activity_options[0]  %>



          <div class="col-xs-12">
            <div class="column-spread">
              <p class="add-description">When?</p>
              <div class="column-border">

                <i class="fa fa-angle-down" aria-hidden="true"></i>

                <div class="selector offered_datetime_text_selector selector-margin-bottom no-margin">
                  <% offered_datetime_text_options.each do |option| %>
                    <div><%= option %></div>
                  <% end %>
                </div>
                <i class="fa fa-angle-up" aria-hidden="true"></i>

            </div>
          </div>
          </div>

          <div class="col-xs-12">
            <div class="column-spread">
              <p class="add-description">What?</p>
              <div class="column-border">

                  <i class="fa fa-angle-down" aria-hidden="true"></i>
                <div class="selector activity_selector no-margin">
                  <% activity_options.each do |option| %>
                  <div><%= option %></div>
                  <% end %>
                </div>
                <i class="fa fa-angle-up" aria-hidden="true"></i>

                </div>
            </div>
          </div>

          <div class="col-xs-12">
            <div class="column-spread-button">
              <div class="button-centered">
                <%= f.button :submit, "Go!", :class => "add-plan-button" %>
                <div class="back-btn">
                  <%= link_to "dismiss", listings_path, class: "back-btn" %>
                </div>
              </div>
            </div>
          </div>
          <% end %>


        </div>
      </div>
    </div>
  </div>
</div>

<!-- The if clause is apparently necessary because in one case we load JQuery before the rest of the code and in the other case we want to load JQuery after some code is executed -->
<% if script %>
<script>
  $('.offered_datetime_text_selector').slick({
    centerMode: true,
    centerPadding: '6px',
    slidesToShow: 3,
    arrows: false,
    swipeToSlide: true
  });

    // On before DateTime change
    $('.activity_selector').slick({
      centerMode: true,
      centerPadding: '10px',
      slidesToShow: 5,
      arrows: false,
      swipeToSlide: true,
      draggable: true,
      focusOnSelect: true,
      mobileFirst: true,
      waitForAnimate: false
    });


    // On before DateTime change
    $('.offered_datetime_text_selector').on('beforeChange', function(event, slick, currentSlide, nextSlide){
      var offered_datetime_text_options_a = <%= offered_datetime_text_options.to_json.html_safe %>
      $('#listing_offered_datetime_text').attr('value', offered_datetime_text_options_a[nextSlide]);


    });

    // On before Activity change
    $('.activity_selector').on('beforeChange', function(event, slick, currentSlide, nextSlide){
      var activity_options_a = <%= activity_options.to_json.html_safe %>
      $('#listing_activity').attr('value', activity_options_a[nextSlide]);
    });
  </script>
  <% else %>
  <%= content_for :after_js do %>
  <script>
    $('.offered_datetime_text_selector').slick({
      centerMode: true,
      centerPadding: '6px',
      slidesToShow: 3,
      arrows: false,
      swipeToSlide: true,
      touchMove: true,
      accessibility: true
    });

      // On before DateTime change
      $('.activity_selector').slick({
        centerMode: true,
        centerPadding: '10px',
        slidesToShow: 5,
        arrows: false,
        swipeToSlide: true,
        draggable: true,
        focusOnSelect: true,
        mobileFirst: true,
        waitForAnimate: false,
        touchMove: true,
        accessibility: true
      });


      // On before DateTime change
      $('.offered_datetime_text_selector').on('beforeChange', function(event, slick, currentSlide, nextSlide){
        var offered_datetime_text_options_a = <%= offered_datetime_text_options.to_json.html_safe %>
        $('#listing_offered_datetime_text').attr('value', offered_datetime_text_options_a[nextSlide]);


      });

      // On before Activity change
      $('.activity_selector').on('beforeChange', function(event, slick, currentSlide, nextSlide){
        var activity_options_a = <%= activity_options.to_json.html_safe %>
        $('#listing_activity').attr('value', activity_options_a[nextSlide]);
      });
    </script>
    <% end %>
    <% end %>

app/views/listings/_plan_show.html.erb
<div id="plan-detail">
  <div class="show-card-position">

    <div class="show-card">
      <div class="show-card-top-section">


        <div class="show-card-user">
          <% if listing.photo_exist? %>
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/mwahrlich", class: "show-card-image" %>
          <% else %>
          <%= image_tag listing.user.facebook_picture_url.gsub("square","large"), class: "show-card-image" %>
          <% end %>
        </div>
        <div class="show-card-top-section-infos">
          <div class="show-card-time">
            <%= listing.offered_datetime_text %>
          </div>

          <div class="show-card-activity">
            <%= listing.activity %>
          </div>
        </div>
      </div>

      <div class="show-card-info">

      </div>
      <div class="show-card-link">
        <% unless listing.owns_listing?(current_user) %>
        <%= button_to "Hang out!", listing_meetings_path(listing_id: listing.id, meeting: {status: "active"}), method: :post, class: "show-card-button" %>
        <% end %>

        <% if listing.owns_listing?(current_user) %>
        <%= button_to "Delete your plan", listing_path(listing), method: :delete, class: "show-card-button" %>
        <% end %>
        <br>
        <div class="back-btn">
          <%= link_to "dismiss", listings_path, class: "back-btn" %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/listings/index.html.erb
<div class="profile_background">
  <div id="plan-listings">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

      <!-- Current user meetings -->

      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          <div class="plan-text-centered">
            <h2><strong>My hangouts</strong></h2>
          </div>
        </a>
      </h4>

      <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
        <div class="meeting-card-flex">
        <% if @listings_participation.empty? %>
          <p>Oh sad, looks like you have none... Let's change that!</p>
        <% else %>
          <% @listings_participation.each do |listing| %>
          <% participants = Participant.where(meeting_id: listing.meetings.ids) %>
          <% meeting_id = Meeting.find_by(listing_id: listing.id).id %>
          <%= link_to listing_meeting_path(listing, meeting_id) do  %>
          <div id="<%= listing.id %>" class="plan">
            <div class="meeting-card current-user-meeting-card">
              <div class="meeting-card-user-avatars">

                <%= image_tag participants[0].user.facebook_picture_url, class: "meeting-card-avatar-current" %>
                <%= image_tag participants[1].user.facebook_picture_url, class: "meeting-card-avatar-user" %>

              </div>
              <div class="meeting-card-info">
                <div class="meeting-card-emoji-round">
                  <p class="meeting-card-emoji"><%= listing.activity %></p>
                </div>
                <p class="meeting-card-datetime"><%= listing.offered_datetime_text %></p>
              </div>
            </div>
          </div>
          <% end %>
          <% end %>
          <% end %>
        </div>
      </div>



      <!-- Current user listings -->
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" href="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <div class="plan-text-centered">
            <h2><strong>My plans</strong></h2>
          </div>
        </a>
      </h4>

      <div id="collapseTwo" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingTwo">
        <div class="plan-card-flex">
          <% current_user.listings_without_match.each_with_index do |listing, index| %>
          <div id="<%= listing.id %>" class="plan listing">
            <div class="plan-card current-user-plan-card">

              <div class="plan-card-info">
                <div class="plan-card-emoji-round">
                  <p class="plan-card-emoji"><%= listing.activity %></p>
                </div>
                <p class="plan-card-datetime"><%= listing.offered_datetime_text %></p>
              </div>
            </div>
          </div>
          <% end %>
          <div class="plan">
            <div class="plan-card-add">
              <div class="plan-card-info">
                <%= link_to new_listing_path, method: :get, remote: true do %>
                <i class="fa fa-plus-circle add-button-size" aria-hidden="true"></i>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>


      <!-- Friends listings -->


      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          <div class="plan-text-centered">
            <h2><strong>Plans by friends!</strong></h2>
          </div>
        </a>
      </h4>


      <div id="collapseThree" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingThree">
        <div class="panel-body panel-border-negative">
          <div class="plan-listings">
            <% @listings.each do |listing| %>
            <div id="<%= listing.id %>" class="plan listing">
              <% if listing.photo_exist? %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/mwahrlich", class: "img-cirlce" %>
              <% else %>
              <%= image_tag listing.user.facebook_picture_url.gsub("square","large") %>
              <% end %>
              <div class="plan-info">
                <p class="plan-user"><%= listing.user.first_name %></p>
                <p class="plan-emoji"><%= listing.activity %></p>
                <% time_difference = listing.offered_datetime - Time.now %>
                <% if time_difference < 1.hour %>
                <p class="plan-datetime"><%= "NOW" %></p>
                <% else %>
                <% hours_difference = (time_difference/3600).to_i %>
                <p class="plan-datetime"><%= "+" + hours_difference.to_s  + "h" %></p>
                <% end %>
                <div>
                  <%= image_tag ("Chevron_right.svg"), :class => "chevron-size" %>
                  <!-- <i class="fa fa-chevron-right chevron-color" aria-hidden="true"></i> -->
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>

    </div>
  </div>

  <div id="render-plan" class="margin-own-plan-offset">
  </div>

  <div id="render-add-plan" class="margin-own-plan-offset">
  </div>
</div>

<%= content_for :after_js do %>
<script>
  $(document).ready(function(){
    $(".listing").on("click", function(e){
      var listing_id = $(this).attr("id");
      $.ajax({
        type: "GET",
        url: "/listings/" + listing_id,
        contentType: 'application/json',
        dataType: 'script'
      });
    });

    // $(".add-plan-button").on("click", function(e){
    //   $.ajax({
    //     type: "GET",
    //     url: "/listings/new",
    //     contentType: 'application/json',
    //     dataType: 'script'
    //   });
    // });
  });
</script>
<% end %>

app/views/listings/index3.html.erb
<% content_for :navbar_title do %>
Add/choose listing
<% end %>

<div class="plan-card-fixed">
  <div class="plan-text-centered">
    <h2>Your current plans:</h2>
  </div>
  <div class="plan-card-flex">
    <% current_user.listings_without_match.each_with_index do |listing, index| %>
    <div id="<%= listing.id %>" class="plan">
      <div class="plan-card current-user-plan-card">

        <div class="plan-card-info">
          <div class="plan-card-emoji-round">
            <p class="plan-card-emoji"><%= listing.activity %></p>
          </div>
          <p class="plan-card-datetime"><%= listing.offered_datetime_text %></p>
        </div>
      </div>
    </div>
    <% end %>
    <div class="plan">
      <div class="plan-card-add">
        <div class="plan-card-info">
          <%= link_to new_listing_path, method: :get, remote: true do %>
          <i class="fa fa-plus-circle add-button-size" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="margin-own-plan-offset">
  <div id="plan-listings" class="plan-listings">
    <div class="plan-text-centered-body">
      <h2>Plans by friends:</h2>
    </div>
    <% @listings.each do |listing| %>
    <div id="<%= listing.id %>" class="plan">
      <% if listing.photo_exist? %>
      <%= image_tag "https://kitt.lewagon.com/placeholder/users/mwahrlich", class: "img-cirlce" %>
      <% else %>
      <%= image_tag listing.user.facebook_picture_url.gsub("square","large") %>
      <% end %>
      <div class="plan-info">
        <p class="plan-user"><%= listing.user.first_name %></p>
        <p class="plan-emoji"><%= listing.activity %></p>
        <% time_difference = listing.offered_datetime - Time.now %>
        <% if time_difference < 1.hour %>
        <p class="plan-datetime"><%= "NOW" %></p>
        <% else %>
        <% hours_difference = (time_difference/3600).to_i %>
        <p class="plan-datetime"><%= "+" + hours_difference.to_s  + "h" %></p>
        <% end %>
        <div>
        <%= image_tag ("Chevron_right.svg"), :class => "chevron-size" %>
          <!-- <i class="fa fa-chevron-right chevron-color" aria-hidden="true"></i> -->
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<div id="render-plan" class="margin-own-plan-offset">
</div>

<div id="render-add-plan" class="margin-own-plan-offset">
</div>



<%= content_for :after_js do %>
<script>
  $(document).ready(function(){
    $(".plan").on("click", function(e){
      var listing_id = $(this).attr("id");
      $.ajax({
        type: "GET",
        url: "/listings/" + listing_id,
        contentType: 'application/json',
        dataType: 'script'
      });
    });

    // $(".add-plan-button").on("click", function(e){
    //   $.ajax({
    //     type: "GET",
    //     url: "/listings/new",
    //     contentType: 'application/json',
    //     dataType: 'script'
    //   });
    // });
  });
</script>
<% end %>

app/views/listings/new.html.erb
  <%= render "new_plan", listing: @listing, offered_datetime_text_options: @offered_datetime_text_options, activity_options: @activity_options, script: false %>

app/views/listings/new.js.erb
$("#plan-listings").fadeOut();
$("#render-add-plan").html("<%= j render "new_plan", listing: @listing, offered_datetime_text_options: @offered_datetime_text_options, activity_options: @activity_options, script: true %>");
// $("#add-plan").fadeIn();
$("#render-add-plan").addClass("negative-body-wrapper");
$("#add-plan").addClass("magictime swashIn");

app/views/listings/show.html.erb
  <%= render "plan_show", listing: @listing %>

app/views/listings/show.js.erb
$("#plan-listings").fadeOut();

$("#render-plan").html("<%= j render "plan_show", listing: @listing %>");
$("#render-plan").addClass("negative-body-wrapper");
$("#plan-detail").addClass("magictime swashIn");