config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :blacklists, only: [ :new, :create, :destroy ]
  resources :users, only: [ :show, :edit, :update ]
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :listings, only: [ :index, :show, :new, :create, :destroy ] do
    resources :meetings, only: [ :create, :show ]
  end

  resources :meetings, only: [ :index, :edit, :update ]

  post 'twilio/voice' => 'twilio#voice'

  resources :chat_rooms, only: [ :show ] do
    resources :messages, only: [ :create ]
  end

  mount Attachinary::Engine => "/attachinary"
  mount ActionCable.server => "/cable"

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  has_many :listings
  has_many :messages, dependent: :destroy
  has_many :participants
  has_many :meetings, through: :listings
  has_many :blacklistings,  class_name:  "Blacklist",
                            foreign_key: "user_id",
                            dependent:   :destroy
  has_many :blacklisted,  class_name:  "Blacklist",
                          foreign_key: "friend_id",
                          dependent:   :destroy
  has_many :blacklisted_friends, through: :blacklistings,  source: :friend
  has_many :blacklisting_friends, through: :blacklisted,  source: :user


  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def listings_without_match
    listings.select { |listing| listing.status == "open" }
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?

      sign_in user, event: :authentication
      # set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
      redirect_to new_listing_path
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   def show
    # friends list
    @user = current_user
    if Rails.env.development?
      @user_friends = User.pluck(:first_name, :uid).map { |user| {"id" => user[1], "name" => user[0]}}
    else
      @user_friends = FacebookApiService.new(current_user.token).friends
    end
    @blacklist = Blacklist.new

    # listings overview
    user_id = current_user.id
    @blacklist_friends = Blacklist.where(user_id: user_id)
    @listings = Listing.where(user_id: user_id).where.not(status: "expired")
    @meeting = Meeting.where(listing_id: @listings.ids)

    #overview of huddles I participated in
    meeting_ids = Participant.where(user_id: @user.id).pluck(:meeting_id)
    meetings = Meeting.where(id: meeting_ids, status: "active")
    @listings_participation = Listing.where(id: meetings.map(&:listing_id)).order("created_at ASC")
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    current_user.update(user_params)
    redirect_to user_path(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:phone_number, :location)
  end
end

app/views/users/edit.html.erb
 <%= simple_form_for(@user) do |f| %>
    <%= f.input :phone_number %>
    <%= f.input :location %>
    <%= link_to "update", user_path(@user), method: :patch, class: "btn btn-primary" %>
  <% end %>

app/views/users/show.html.erb
<div class="profile_background">

  <% content_for :navbar_title do %>
  Manage profile
  <% end %>
  <div class="profile_heading">
    <h1><strong><%= "Hi " + @user.first_name %></strong></h1>
    <p>
      <%= current_user.phone_number %> (<%= current_user.location %>)
    </p>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

      <div class="panel-heading panel-heading-padding" role="tab" id="headingFour">
        <a role="button" data-toggle="collapse" href="#collapseFour" aria-expanded="true" aria-controls="collapseFour">
          <div class="edit-btn">
            <i class="fa fa-pencil" aria-hidden="true"></i>
          </div>
        </a>
      </div>
    </div>
  </div>

  <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
    <div class="panel-body">
      <div class="profile_form">
        <%= simple_form_for(@user) do |f| %>
        <%= f.input :phone_number, lable: @user.phone_number %>
        <%= f.input :location, lable: @user.location %>
        <div class="button-profile-center">
          <%= f.submit "update", class: "profile_button" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          <div class="profile_sub_heading">
            <p><strong>Your hangouts:</strong></p>
          </div>
        </a>
      </h4>
    </div>

    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <% if @listings_participation.empty? %>
      <p class="no-plan">Oh sad, looks like you have none... Let's change that!</p>
      <div class="panel-button">
        <%= link_to "Find a Hangout!", listings_path, class: "profile_button" %>
      </div>
      <% else %>
      <div class="panel-body">
        <% @listings_participation.each do |listing| %>
        <% meeting_id = Meeting.find_by(listing_id: listing.id).id %>
        <% participants = Participant.where(meeting_id: listing.meetings.ids) %>
        <div class="listing-card-wrapper">
          <div class="listing_card">
            <div class="listing_card_link">
                <%= link_to listing_meeting_path(listing, meeting_id) do  %>
                <div class="meeting-card-user-avatars">

                <%= image_tag participants[0].user.facebook_picture_url, class: "meeting-card-avatar-current" %>
                <%= image_tag participants[1].user.facebook_picture_url, class: "meeting-card-avatar-user" %>

              </div>
              <div class="listing-card-infos">
                <p class="plan-emoji"><%= listing.activity %></p>
                <p class="plan-datetime"><%= listing.offered_datetime_text%></p>
              <% end %>
              </div>
            </div>
            <!-- <i class="fa fa-chevron-right chevron-color" aria-hidden="true"></i> -->
            <div>
              <%= link_to "I'm out", meeting_path(meeting_id), method: :patch, class: "opt-out-btn" %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>



    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" href="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <div class="profile_sub_heading">
            <p><strong>Your plans:</strong></p>
          </div>
        </a>
      </h4>
    </div>

    <div id="collapseTwo" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingTwo">
      <% if @listings.empty? %>
      <p class="no-plan">All you need is a plan! A plan is all you need!</p>
      <div class="panel-button">
        <%= link_to "Add a Plan!", new_listing_path, class: "profile_button" %>
      </div>
      <% else %>
      <% @listings.each do |listing| %>
      <% meeting = Meeting.where(listing_id: listing.id).first %>
      <% participant = Participant.where(meeting_id: meeting.id) if meeting %>
      <div class="listing-card-wrapper">
        <%= link_to listing_path(listing) do  %>
        <div class="listing_card <%= 'listing_expired' if listing.status == 'expired' %>">
          <p class="plan-emoji"><%= listing.activity %></p>
          <p class="plan-datetime"><%= listing.offered_datetime_text%></p>
          <i class="fa fa-chevron-right chevron-color" aria-hidden="true"></i>
        </div>
        <% end %>
      </div>
      <% end %>
      <% end %>
    </div>

    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          <div class="profile_sub_heading">
            <p><strong>Manage which friends can contact and see you!</strong></p>
          </div>
        </a>
      </h4>
    </div>

    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">

        <p>If you blacklist a friend, you won't see any of his postings and your friend won't see any of yours anymore. But don't worry, your friend will not know that you blacklisted him or her!</p>

        <% @user_friends.each do |friend| %>
        <% facebook_friend = User.find_by(uid: friend["id"]) %>
        <% facebook_friend_id = facebook_friend.id %>

        <% blacklist = Blacklist.where(user_id: @user.id).where(friend_id: facebook_friend_id).first %>

        <div class="friends_card <%= "blacklisted" if blacklist  %>">

          <div class="col-xs-3">
            <div class="friend_photo_wrapper">
              <%= image_tag facebook_friend.facebook_picture_url.gsub("square","large"), class: "friend_photo" %>
            </div>
          </div>

          <div class="col-xs-6">
            <div class="friends_name">
              <p><%= friend["name"].partition(" ").first %></p>
            </div>
          </div>

          <div class="col-xs-3">
            <div class="blacklist_button">
              <%= link_to "Block", blacklists_path(friend_id: facebook_friend_id), method: :post unless blacklist  %>
              <%= link_to "Unblock", blacklist_path(blacklist.id), method: :delete if blacklist %>
            </div>
          </div>

        </div>

        <% end %>
      </div>


    </div>
  </div>


</div>