config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :blacklists, only: [ :new, :create, :destroy ]
  resources :users, only: [ :show, :edit, :update ]
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :listings, only: [ :index, :show, :new, :create, :destroy ] do
    resources :meetings, only: [ :create, :show ]
  end

  resources :meetings, only: [ :index, :edit, :update ]

  post 'twilio/voice' => 'twilio#voice'

  resources :chat_rooms, only: [ :show ] do
    resources :messages, only: [ :create ]
  end

  mount Attachinary::Engine => "/attachinary"
  mount ActionCable.server => "/cable"

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed">

<!--  <div class="navbar-title">
    <%= content_for?(:navbar_title) ? yield(:navbar_title) : "Meet friends, be happy!" %>
  </div> -->

  <% if current_user %>
    <%= link_to raw('<i class="fa fa-chevron-left back-button"></i>'), :back %>
    <%= link_to raw('<div class="nav-bar-button">my plans</div>'), listings_path + "#you"  %>
    <%= link_to raw('<div class="nav-bar-button">friends&#39; plans</div>'), listings_path + "#friends" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">
    <% if user_signed_in? %>

    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <div class="avatar-protection dropdown-toggle" id="navbar-wagon-menu", data-toggle="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
          <%= image_tag avatar_url, class: "avatar" %>
        </div>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to user_path(current_user) do %>
            <i class="fa fa-cog"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
<!--           <li>
            <%= link_to listings_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
          <li>
            <%= link_to new_listing_path do %>
            <i class="fa fa-plus-circle"></i>  <%= t(".profile", default: "Add Plan") %>
            <% end %>
          </li> -->
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <% end %>
  </div>


</div>